// Shared translations for the React site and the standalone download list.
export const english = {
'研究':'Research','新闻动态':'News','发现与动态':'News','论文':'Publications','团队':'People','实验室':'Lab','文章':'Articles','主页':'Home','研究方向':'Research Areas',
'看见大脑，理解生命。':'Imaging the brain. Understanding life.','让微小，清晰可见。':'Making the microscopic visible.','从信号，重建内部。':'Reconstructing structures from signals.','拓展成像的边界。':'Advancing imaging capabilities.',
'光声脑成像':'Photoacoustic Brain Imaging','光声显微成像':'Photoacoustic Microscopy','阵列式光声断层成像':'Array-Based Photoacoustic Tomography','热声成像':'Thermoacoustic Imaging','脑成像':'Brain Imaging','显微成像':'Microscopy','断层成像':'Tomography','微波激发与声学检测':'Microwave excitation and acoustic detection',
'研究脑血管结构、血流动力学及相关成像方法。':'We investigate cerebral vascular structure, hemodynamics and related imaging methods.',
'从微血管到组织结构，发展高时空分辨率的光声显微成像技术。':'We develop photoacoustic microscopy with high spatial and temporal resolution, from microvessels to tissue structure.',
'结合光学激发与声学探测，研究多尺度的组织成像。':'We combine optical excitation and acoustic detection to image tissues across multiple scales.',
'探索微波激发与声学检测，发展热声成像与相关技术。':'We explore microwave excitation and acoustic detection to advance thermoacoustic imaging and related techniques.',
'实验室主要开展光声脑成像、光声显微成像、阵列式光声断层成像和热声成像研究。':'Our research spans photoacoustic brain imaging, photoacoustic microscopy, array-based photoacoustic tomography and thermoacoustic imaging.',
'探索更多':'Explore more','查看全部':'View all','MFOIL 首页':'MFOIL home','关闭 / ESC':'Close / ESC','关闭':'Close','菜单':'Menu','主导航':'Main navigation','加入我们 / RESEARCH WITH US':'RESEARCH WITH US','加入我们':'Join us','联系实验室':'Contact the Lab','加入 MFOIL':'Join MFOIL',
'南方科技大学 · 生物医学工程系':'SUSTech · Department of Biomedical Engineering','广东省深圳市南山区学苑大道 1088 号':'1088 Xueyuan Avenue, Nanshan District, Shenzhen, Guangdong','深圳市南山区学苑大道 1088 号':'1088 Xueyuan Avenue, Nanshan District, Shenzhen','南方科技大学多功能光学成像实验室':'Multi-Functional Optical Imaging Lab, SUSTech','多功能光学成像实验室':'Multi-Functional Optical Imaging Lab','南方科技大学':'Southern University of Science and Technology','内容与原始附件':'Content & Original Files','论文年档':'Publication Archives','实验室动态':'Lab News','阅读全文':'Read article','READ PUBLICATION / 查看论文':'READ PUBLICATION','SEARCH / 搜索':'SEARCH','EXPLORE / 探索':'EXPLORE',
'搜索标题、关键词或人名':'Search titles, keywords or names','清空':'Clear','没有找到匹配内容。':'No matching results.','试试其他关键词，或清除筛选条件。':'Try another keyword or clear the filters.','全部年份':'All years','全部':'All','研究与动态':'Research News','荣誉与活动':'Awards & Events',
'按时间查看研究进展、论文发表、学术交流与实验室活动。':'Research updates, publications, academic exchanges and lab events in chronological order.','按年份筛选文章':'Filter articles by year',
'团队成员':'Our People','实验室教师、研究人员、学生及校友的个人资料。':'Profiles of our faculty, researchers, students and alumni.','全部成员档案':'All profiles','现有团队与校友去向':'Current members & alumni','PI / 奚磊':'PI / Lei Xi','搜索姓名、研究或经历':'Search names, research or experience',
'包含历史成员与校友，档案不代表当前在岗名单；身份与去向请参阅原站团队记录。':'These archives include former members and alumni, not only current staff. Consult the original team records for roles and destinations.','Principal Investigator / 教授':'Principal Investigator / Professor','成员档案 / Profile':'Member Profile',
'实验室原始光声显微成像图':'Original photoacoustic microscopy images from the lab','下列相关论文按题名与关键词归类，具体研究内容以原文为准。':'Related publications are grouped by titles and keywords. Refer to the original papers for the full research context.','阅读原站研究内容':'Read the original research overview','相关论文':'Related Publications','研究资料':'Research Resources','浏览全部论文':'Browse all publications','查看各研究方向的介绍、相关论文与原始资料。':'Explore research overviews, related publications and original materials.','查看完整原站研究记录':'View the original research archive','管理登录':'Administrator login','相关资料与链接':'Related Resources & Links','全部文章':'All articles',
'内容来自原站档案。原始发布日期保留，未改写为近期消息。':'Content is preserved from the original website with its original publication date; it is not a recent update.','原文配图':'Original article image','更多实验室动态':'More Lab News','原站内容档案 · 文字与可用图片已迁入新版':'Original website archive · Text and available images have been migrated',
'实验室介绍':'About the Lab','实验室集体照片':'Lab group photo','研究概况':'Research Overview','MFOIL 隶属于南方科技大学生物医学工程系，围绕光声与热声等生物医学成像技术开展研究。':'MFOIL is part of the Department of Biomedical Engineering at SUSTech. Our research focuses on biomedical imaging, including photoacoustic and thermoacoustic techniques.','认识 PI · 奚磊':'Meet the PI · Lei Xi','邮编 518055':'Postal code 518055','实验室相册':'Lab Gallery','打开影像档案':'Open the image archive','招生与招聘':'Open Positions','博士后 · 博士研究生 · 研究助理':'Postdoctoral Fellows · PhD Students · Research Assistants','招聘信息':'Recruitment Information','以下为原站招聘信息，具体岗位开放情况请联系实验室确认。':'This recruitment notice is from the original website. Contact the lab to confirm current openings and terms.','联系 PI · xilei@sustech.edu.cn':'Contact the PI · xilei@sustech.edu.cn',
'全部图片':'All images','研究图像与实验室相册':'Research Images & Lab Gallery','实验室相册、研究图像与原始图片资源。点击图片可放大查看。':'Explore lab photos, research images and original image resources. Select an image to enlarge it.','图片分类':'Image categories','内容档案':'Content Archive','视频':'Videos','资料归档':'Archives','查看原站页面、论文 PDF、成员资料及图片等归档文件。':'Browse archived website pages, paper PDFs, member profiles and images.','原始附件':'Original Files','文件类型':'File type','图片':'Image','全文搜索所有原站记录':'Search the full text of original records','搜索原始文件名':'Search original filenames','查看档案':'View archive','原始文件保持原名。旧 SWF 格式现代浏览器无法直接播放，可下载保留。部分原始文件有重复版本。':'Downloads retain their original filenames; English labels are used for display. Modern browsers cannot play legacy SWF files directly, but you can download them. Some files have duplicate versions.','MB / 下载':'MB / Download','这个页面还没有被找到。':'Page not found.','搜索全部档案':'Search all archives','查看原始图片':'View original image','原始图片':'Original image','完整档案':'Full Archive','影像档案':'Image Archive','研究档案':'Research Archive','跳到主要内容':'Skip to main content',
'光声与热声成像技术研究':'Photoacoustic & Thermoacoustic Imaging Research','查看研究方向':'Explore our research','关于实验室':'About the lab','观看原始成像视频':'Watch the original imaging video','实验室精选影像':'Selected lab images','光声显微成像原始图':'Original photoacoustic microscopy image','光声显微成像原始科研图片':'Original photoacoustic microscopy research image','光声显微成像 / 原始图像':'Photoacoustic Microscopy / Original Images','成像仪器':'Imaging Instruments','MFOIL 实验室相册':'MFOIL Lab Gallery','实验室日常':'Life in the Lab','关于 MFOIL':'ABOUT MFOIL',
'多功能光学成像实验室隶属于南方科技大学生物医学工程系。我们发展光声与热声成像技术，研究从微观结构到生物功能的成像方法。':'The Multi-Functional Optical Imaging Lab is part of the Department of Biomedical Engineering at SUSTech. We develop photoacoustic and thermoacoustic imaging techniques to study microscopic structures and biological function.',
'MFOIL 实验室相册原始照片':'Original photograph from the MFOIL lab gallery','Inside MFOIL / 实验室相册':'Inside MFOIL / Lab Gallery','光学 / 声学 / 生物医学':'OPTICS / ACOUSTICS / BIOMEDICINE','研究展示':'RESEARCH HIGHLIGHTS','查看实验室的成像系统、研究图像与研究方向。':'Explore our imaging systems, scientific images and research areas.','光声显微成像：成像系统、兔眼与人唇的微血管图像':'Photoacoustic microscopy: imaging system and microvascular images of a rabbit eye and human lips','查看原始图':'View original image','查看相关报道':'Read the related article','实验室原始显微成像图':'Original microscopy image from the lab','实验室原始微血管成像图':'Original microvascular image from the lab','微血管的细节':'Microvascular Detail','实验室科研影像档案':'Lab Research Image Archive','全部研究':'All research','查看团队成员':'Meet our people','最新论文':'LATEST PUBLICATIONS','完整论文库':'All publications','研究论文':'Research Papers','查看':'View','MFOIL 实验室集体照片':'MFOIL lab group photo','所有文章':'All articles','页脚导航':'Footer navigation','回到 MFOIL 首页':'Back to MFOIL home',
'血管成像切片局部，底部深度文字已裁去':'Vascular imaging section with the bottom depth annotation cropped out','实验室血管成像视频局部，原速正放与倒放循环':'Lab vascular imaging video, looping forward and backward at original speed','视频不可用，正在展示静态封面':'Video unavailable; showing a still image','暂停首屏成像视频':'Pause the hero imaging video','播放首屏成像视频':'Play the hero imaging video','静态影像':'Still image','暂停影像':'Pause video','播放影像':'Play video',
'我们探索光声与多模态成像技术，连接基础研究与临床应用。欢迎博士后、博士研究生及研究助理加入南方科技大学多功能光学影像实验室。':'We explore photoacoustic and multimodal imaging, connecting fundamental research with clinical applications. We welcome postdoctoral fellows, PhD students and research assistants to the Multi-Functional Optical Imaging Lab at SUSTech.','日期未记录':'Date not recorded','同项研究原图 · 探头结构示意':'Original figure from the same study · Probe schematic','动态，按日期从新到旧排列':'News, newest first',
'日期请填写 YYYY、YYYY-MM 或 YYYY-MM-DD。':'Use YYYY, YYYY-MM or YYYY-MM-DD.','请填写有效日期。':'Enter a valid date.','作者、题目和期刊不能为空。':'Authors, title and journal are required.','修订文献信息':'Edit citation information','确认本条文献信息':'Confirm Citation Details','取消':'Cancel','姓名按“姓 名”每行一位，保留 # 和 *。修改仅保存在当前浏览器，不覆盖网站原始记录。':'Enter one author per line in family-name given-name order, preserving # and *. Changes are saved only in this browser and do not overwrite the original website records.','作者名单':'Authors','论文题目':'Paper title','期刊':'Journal','卷号':'Volume','期号（可为空）':'Issue (optional)','页码 / 文章号':'Pages / article number','正式发表日期（可只填年或年月）':'Publication date (year or year-month accepted)','在线发表日期（可为空）':'Online publication date (optional)','确认并保存本条':'Confirm & save',
'已生成 CSV 明细，可用 Excel 打开。':'CSV generated. You can open it in Excel.','已生成':'Generated','篇文献的 Word 下载。':'references as a Word download.','未完成：':'Could not complete: ','修订已保存在当前浏览器。':'Corrections saved in this browser.','浏览器无法保存修订，本次仍可预览和导出；刷新后修改将丢失。':'This browser could not save corrections. You can still preview and export them, but changes will be lost on refresh.','返回论文库':'Back to publications','返回首页':'Back to home','返回新闻动态':'Back to news','返回研究方向':'Back to research','返回影像档案':'Back to images','返回实验室':'Back to the lab','返回团队':'Back to people','返回完整档案':'Back to the archive','返回导航':'Back navigation',
'整理成果':'Organize Publications','筛选、统计与文献导出':'Filter, count and export references','选定年份和文献，按实验室模板直接导出。作者标记、期刊格式和发表日期一并保留。':'Select years and papers, then export using the lab template. Author markers, journal formatting and publication dates are retained.','筛选与导出设置':'Filter and export settings','起始年份':'Start year','结束年份':'End year','统计与日期口径':'Date basis','正式卷期 / 登记发表日期':'Issue / registered publication date','在线发表日期':'Online publication date','原站归档年份 / 原记录日期':'Original archive year / recorded date','排序':'Sort','从新到旧':'Newest first','从旧到新':'Oldest first','搜索作者、题目或期刊':'Search authors, titles or journals','按年份分组':'Group by year','仅看待核对':'Needs review only','请填写有效的四位年份，起始年份不能晚于结束年份。':'Enter valid four-digit years. The start year must not be later than the end year.',
'范围包含起止年份。日期只保留已知精度，不补月、日。同一 DOI 去重统计；共同一作与通讯作者标记沿用原站，模板示例按所给 Word。引用年份以卷期信息为准。':'The range includes both years. Dates retain their known precision; missing months and days are not invented. Duplicate DOIs are counted once. Equal-contribution and corresponding-author markers follow the original records, and formatting follows the supplied Word template. Citation years follow issue information.',
'篇没有在线日期，当前口径下不计入。':'papers have no online date and are excluded under this date basis.','选中文献统计':'Selected publication statistics','已选 / 共':'selected /','篇符合条件':'matching papers','全选当前结果':'Select all results','取消当前选择':'Clear selection','复制文献':'Copy references','导出统计 CSV':'Export CSV','正在生成…':'Generating...','一键导出 Word':'Export Word','选中的':'Selected:','篇仍有待核对字段':'papers still have fields to review','可在下方查看来源并修订。不会自动猜测姓名或缺失日期；复制、导出均使用当前预览的信息。':'Review sources and make corrections below. Names and missing dates are not guessed. Copy and export use the information in the current preview.','我已了解待核对项，允许按当前信息导出':'I acknowledge the pending items and approve export of the current information.',
'实验室文献格式预览':'Lab citation format preview','文献预览':'Citation Preview','Times New Roman / 仿宋 · 16 磅':'Times New Roman / FangSong · 16 pt','没有符合条件的论文，请调整年份、时间口径或搜索条件。':'No matching papers. Adjust the years, date basis or search terms.','选择':'Select','已人工确认':'Manually confirmed','已匹配公开元数据':'Matched to public metadata','原站记录，待确认':'Original record; confirmation needed','核对 / 修订':'Review / edit','待核对：':'Needs review: ','原始记录与数据来源':'Original Record & Sources','Crossref 登记元数据':'Crossref metadata','论文原文 / DOI':'Original paper / DOI','正式卷期：':'Issue date: ','；在线发表：':'; online: ','；登记发表：':'; registered: ','。数据库匹配不代表所有字段都已人工审核。':'. A database match does not mean that all fields have been manually reviewed.',
'打开本地 PDF':'Open saved PDF','打开 PDF':'Open PDF','原文入口':'Publisher page','查找下载链接':'Find download links','论文详情':'Paper details','PDF 在新标签页打开；若需要认证，请在出版社页面使用学校账号登录。':'PDFs open in a new tab. If authentication is required, sign in through your institution on the publisher website.','文献信息':'Citation','论文插图':'Paper figure','查看原图':'View full image','论文相关入口':'Related resources','返回图文论文库':'Back to publications','全部论文下载清单':'All paper downloads','整理成果与导出':'Organize & export','正文第':'Page',' 页':'','论文来源':'Figure source','实验室光声显微成像结果：小鼠和大鼠的耳部与脑部血管':'Lab photoacoustic microscopy: ear and brain vasculature in mice and rats','光声显微成像 · 实验室研究图像':'Photoacoustic Microscopy · Lab Research Images','论文与研究成果':'Publications & Research','浏览实验室的研究图像与论文，了解光声、热声及多模态成像研究。':'Explore our research in photoacoustic, thermoacoustic and multimodal imaging through publications and scientific images.','PDF 下载清单':'PDF Downloads','论文浏览':'Browse publications','全部论文':'All publications','收起筛选':'Hide filters','搜索与筛选':'Search & filter','已筛选':'Filtered','搜索论文':'Search papers','输入论文题目、作者或期刊':'Search by title, author or journal','发表年份':'Publication year','清除筛选':'Clear filters','按年份从新到旧排列':'Newest first','篇论文':'papers','没有符合条件的论文':'No matching papers','试试其他关键词或年份。':'Try another keyword or year.','查阅与整理':'Browse & Organize','按年份统计论文，按实验室格式导出文献。':'Count papers by year and export citations in the lab format.','原始论文列表与专利':'Original Publications & Patents','PDF 与原始附件':'PDFs & Original Files',
'未记录':'Not recorded','作者缺失':'Missing authors','期刊缺失':'Missing journal','卷号缺失':'Missing volume','页码或文章号缺失':'Missing pages or article number','在线发表日期缺失':'Missing online publication date','正式发表日期未确认，仅保留年份':'Publication date unconfirmed; year only','[期刊待补]':'[Journal pending]','已复制带格式文献，可粘贴到 Word。':'Formatted references copied. Paste them into Word.','浏览器不支持复制，请下载 Word。':'Copying is not supported in this browser. Download Word instead.','已复制纯文本；完整字体和上标请使用 Word 导出。':'Plain text copied. Use Word export to preserve fonts and superscripts.','序号':'No.','统计年份':'Reporting year','作者':'Authors','题目':'Title','卷':'Volume','期':'Issue','页码或文章号':'Pages / article number','发表时间':'Publication date','待核对项':'Review items','成果':'Publications','篇':'papers','年':'','月':'','日':'',
'原站题名与发表题名有差异，已按来源更新':'The original title differs from the published title; updated from the source.','部分作者贡献标记未能对应，请核对 # / *':'Some contribution markers could not be matched. Review # / *.','登记作者人数与原站不同，请确认名单':'The registered author count differs from the original website. Confirm the author list.','未匹配登记元数据，作者姓名顺序及书目信息待确认':'No registered metadata match. Confirm author name order and bibliographic details.','正文插图':'Article figure','研究报道中的探头结构图':'Probe schematic from the research report','对应论文原图 · 猕猴脑皮层成像':'Original paper figure · Rhesus cerebral cortex imaging','对应论文原图':'Original paper figure','同项研究原图 · 可拆卸头戴显微镜':'Original figure from the same study · Detachable head-mounted microscope','对应研究配图':'Figure from the corresponding study','实验室合影 · 招聘配图，非发布日期现场照':'Lab group photo used for recruitment; not taken on the posting date','南方科技大学多功能光学影像实验室团队合影':'MFOIL lab group photo, SUSTech',
'南方科技大学多功能光学影像实验室招聘博士后、博士研究生、研究助理':'MFOIL at SUSTech: Open Positions for Postdoctoral Fellows, PhD Students and Research Assistants',
'上一页':'Previous page','下一页':'Next page','登录':'Log in','注册':'Register','留言板':'Message Board','姓名':'Name','邮箱':'Email','电话':'Phone','内容':'Content','验证码':'Verification code','提交留言':'Submit message','《互联网跟帖评论服务管理规定》':'Provisions on the Administration of Internet Comment Services','分享':'Share','联系我们':'Contact Us','确认密码':'Confirm password','密码':'Password','账号':'Account','手机':'Mobile','中国大陆':'Mainland China','中国香港':'Hong Kong','中国澳门':'Macao','中国台湾':'Taiwan','迪拜':'Dubai',
'资源库文件':'Resource-library-files','修改前':'Previous-version','QQ图片':'QQ-image','QQ截图':'QQ-screenshot','微信图片':'WeChat-image','关于我们':'About-us','新闻':'News','横幅':'Banner','科技':'Technology','首页':'Home','迎新':'Welcome','倒影里的九华精舍':'Reflections-of-Jiuhua-House','图书馆':'Library','云海·校前区':'Clouds-over-campus-entrance','第二教学楼':'Teaching-Building-2','三百年的古榕':'Three-hundred-year-old-banyan','行云':'Drifting-clouds','未标题':'Untitled','行政楼·屹然矗立':'Administration-building','行政楼':'Administration-building','生物医学工程系LOGO':'Biomedical-Engineering-Logo','校名石和图书馆':'University-name-stone-and-library','通向知识的阶梯':'Steps-to-knowledge','止水':'Still-water','第二科研楼前面':'Research-Building-2-front','自由的天空':'Open-sky','第一教学楼':'Teaching-Building-1','刘强':'Qiang-Liu','李林阳':'Linyang-Li','陈星星':'Xingxing-Chen','郭恒':'Heng-Guo','曾健':'Jian-Zeng','王敏':'Min-Wang','李婷婷':'Tingting-Li','近照':'Recent-photo','秦伟':'Wei-Qin','个人证件照':'ID-photo','证件照':'ID-photo','副本':'Copy','白':'White','刘飞':'Fei-Liu','王玉洁':'Yujie-Wang','齐伟智':'Weizhi-Qi','标题':'Title','空白':'Blank','深圳':'Shenzhen',
'论文 PDF 下载清单':'Paper PDF Downloads','全部论文按年份从新到旧排列。点击“打开 PDF”尝试进入文件；没有直接地址的，点击“原文入口”，在出版社页面选择 PDF。':'Papers are listed newest first. Select Open PDF to access a file, or Publisher page to find the PDF when no direct link is available.','先在同一浏览器完成学校数据库登录。PDF 链接可能仍要求机构认证，或先显示阅读器，不能保证点击即自动保存。下载文件放入项目的':'Sign in to your university database in this browser first. PDF links may require institutional authentication or open a reader rather than save automatically. Place downloaded files in','，无需重命名。下方勾选仅记录你的手动进度，不会自动检测下载。':', without renaming them. Checkboxes track your manual progress; downloads are not detected automatically.','搜索标题、作者关键词、DOI 或论文编号':'Search titles, author keywords, DOI or paper number','筛选':'Filter','缺图且待下载':'Missing figure; awaiting download','已有本地 PDF':'Saved PDF available','尚未手动勾选':'Not marked as downloaded','年份':'Year','下载链接表 CSV':'Download links CSV','链接表保留 DOI 与原文入口；按规则生成的 PDF 地址已单独标注，实际权限以出版社页面为准。':'The list retains DOIs and publisher links. Pattern-generated PDF links are labeled separately; access is subject to the publisher.','当前':'Shown','手动勾选':'Marked downloaded','缺图，优先下载':'Missing figure; prioritize download','已有配图，可选下载':'Figure available; download optional','链接待补':'Link pending','我已下载':'Downloaded','按 DOI 规则生成，未验证直达':'Generated from DOI pattern; direct access not verified','原站 PDF 链接':'Original website PDF link','出版社 PDF 链接':'Publisher PDF link','本地 PDF':'Saved PDF',
};

// Archived recruitment terms are translated faithfully, not updated or endorsed.
Object.assign(english, {
'课题组简介：多功能光学影像实验室（Multi-Functional Optical Imaging Lab,MFOIL）由现南方科技大学生物医学工程系奚磊教授于2014年11月建立。课题组主要从事光声层析成像（photoacoustictomography）、光声显微成像（photoacoustic microscopy）、光声内窥（photoacoustic endoscopy）、光学相干层析成像（opticalcoherence tomography）、热声成像（thermoacoustic tomography）、扩散光学层析成像（diffuse optical tomography）、荧光分子成像（fluorescencemolecular tomography）等各类成像技术在基础和临床中的应用研究。':'Lab overview: The Multi-Functional Optical Imaging Lab (MFOIL) was founded in November 2014 by Professor Lei Xi, now in the Department of Biomedical Engineering at SUSTech. The lab investigates fundamental and clinical applications of photoacoustic tomography, photoacoustic microscopy, photoacoustic endoscopy, optical coherence tomography, thermoacoustic tomography, diffuse optical tomography and fluorescence molecular tomography.',
'课题组主页：mfoil.bme.sustech.edu.cn (备用：www.mfoil.org)':'Lab website: mfoil.bme.sustech.edu.cn (alternative: www.mfoil.org)',
'工作地点:　南方科技大学':'Location: Southern University of Science and Technology',
'一、研究助理教授岗位要求及待遇（1-2名）：':'1. Research Assistant Professor: Requirements and Benefits (1-2 positions)',
'1、具有博士学位；':'1. A doctoral degree is required.',
'2、具有光学、声学、生物医学工程等背景者优先；':'2. Backgrounds in optics, acoustics, biomedical engineering or related disciplines are preferred.',
'3、动手能力强，有责任心、能够吃苦耐劳、对研发各类成像仪器有浓厚兴趣；':'3. Strong practical skills, responsibility, perseverance and a keen interest in developing imaging instruments.',
'4、发表过4-6篇相应领域主流SCI文章，具备较好的英文读、写、说的能力；':'4. Four to six publications in mainstream SCI-indexed journals in a relevant field, with good English reading, writing and speaking skills.',
'5、根据个人的科研资历，年薪30-35万。符合要求者可以申请深圳相关人才计划，海外博士后可以申请孔雀计划，深圳市补贴160-200万。':'5. Annual salary of RMB 300,000-350,000, depending on research experience. Eligible applicants may apply for Shenzhen talent programs. Overseas postdoctoral researchers may apply for the Peacock Plan, with municipal subsidies of RMB 1.6-2 million, as stated in this archived notice.',
'二、博士后岗位要求及待遇（1-2名）：':'2. Postdoctoral Fellows: Requirements and Benefits (1-2 positions)',
'1、具有博士学位或近期能够通过博士答辩；':'1. A doctoral degree, or an expected successful dissertation defense in the near future.',
'2、具有电磁场与电磁波、光学、声学、生物医学工程等背景者优先；':'2. Backgrounds in electromagnetic fields and waves, optics, acoustics, biomedical engineering or related disciplines are preferred.',
'4、发表过1-2篇相应领域主流SCI文章，具备较好的英文读、写、说的能力':'4. One to two publications in mainstream SCI-indexed journals in a relevant field, with good English reading, writing and speaking skills.',
'5、根据个人的科研资历，年薪30万以上，其中包括深圳市政府每年免税生活补助18万元。除此以外，学校承担五险一金。条件优秀的申请人可以入选校长卓越奖励计划，合计35万年薪。学校为每位博士后提供每两年2.5万元的学术交流资助。课题组为优秀博士后提供额外的津贴和奖励。符合要求者可以申请深圳相关人才计划，海外博士后可以申请孔雀计划，深圳市补贴160-200万。':'5. As stated in this archived notice, annual compensation exceeds RMB 300,000 depending on research experience, including an annual tax-exempt municipal living allowance of RMB 180,000. The university also provides statutory social insurance and a housing fund. Outstanding applicants may receive a total annual salary of RMB 350,000 through the Presidential Excellence Award. Each postdoctoral fellow receives RMB 25,000 for academic exchanges every two years. The lab offers additional allowances and awards for excellent performance. Eligible applicants may apply for Shenzhen talent programs; overseas postdoctoral researchers may apply for the Peacock Plan, with municipal subsidies of RMB 1.6-2 million.',
'6、课题组提供充足的科研条件，协助博士后本人作为负责人申请中国博士后科学基金、国家自然科学基金以及广东省、及深圳市各级科研项目。依据自身符合要求，在站和出站留深博士后可以申请深圳相关人才计划，深圳市提供5年160万的奖励津贴(免税)；':'6. The lab provides research resources and supports fellows in applying as principal investigators for the China Postdoctoral Science Foundation, National Natural Science Foundation of China, and Guangdong and Shenzhen research grants. Eligible current or former fellows remaining in Shenzhen may apply for talent programs offering a tax-exempt RMB 1.6 million award over five years, as stated in this archived notice.',
'7、对于符合最新《深圳市新引进人才租房和生活补贴》相关政策要求的博士后，在深圳落户后，可申请深圳市一次性租房和生活补贴3万元（免税，自行网上申请）；':'7. The archived notice states that fellows meeting the Shenzhen housing and living allowance policy requirements may apply online for a one-off, tax-exempt RMB 30,000 allowance after obtaining Shenzhen household registration.',
'8、博士后出站选择留深从事科研工作，且与本市企事业单位签订3年以上劳动（聘用）合同的，可以申请深圳市博士后留深来深科研资助，深圳市政府给予每人每年10万元科研资助，共资助3年。':'8. The archived notice states that fellows who remain in Shenzhen for research after completing their appointment and sign an employment contract of at least three years with a local organization may apply for municipal research funding of RMB 100,000 per year for three years.',
'9、对于优秀的出站博士后将积极推荐协助其申请南方科技大学研究助理教授等岗位。':'9. Outstanding fellows completing their appointments will receive recommendations and support when applying for Research Assistant Professor and related positions at SUSTech.',
'三、博士生要求及待遇（1-2名/年）：':'3. PhD Students: Requirements and Benefits (1-2 places per year)',
'1、已经毕业或即将硕士毕业，具有电磁场与电磁波、光学、声学、生物医学工程等背景者优先；':'1. A completed or forthcoming master\'s degree. Backgrounds in electromagnetic fields and waves, optics, acoustics or biomedical engineering are preferred.',
'2、热爱科研、具有高度的主动性、勤奋努力、有强烈的求知欲；':'2. A passion for research, initiative, diligence and intellectual curiosity.',
'3、具有扎实的理论和实验训练，良好的英语听说读写能力，有SCI研究论文者优先；':'3. Strong theoretical and experimental training and good English listening, speaking, reading and writing skills. SCI-indexed publications are an advantage.',
'4、博士生10万/年奖学金；提供良好的实验条件和学习环境；有机会申请与澳门大学、香港大学、香港科大、香港浸会大学的博士生联合项目，在香港澳门期间按当地博士生标准发放全额奖学金。具体的研究生项目与申请方式可参考学校的研究生招生网站：https://gs.sustech.edu.cn/shuoshi2022':'4. This archived notice lists a PhD scholarship of RMB 100,000 per year, with laboratory facilities and a supportive learning environment. Students may apply for joint PhD programs with the University of Macau, the University of Hong Kong, the Hong Kong University of Science and Technology, and Hong Kong Baptist University, with full scholarships at local PhD rates during their stay in Hong Kong or Macau. Program and application information: https://gs.sustech.edu.cn/shuoshi2022',
'四、研究助理要求及待遇（不限）':'4. Research Assistants: Requirements and Benefits (No Fixed Quota)',
'1、光学工程、电磁场与电磁波、声学、生物医学工程等相关专业优秀的本科及以上学历；':'1. An excellent bachelor\'s degree or higher in optical engineering, electromagnetic fields and waves, acoustics, biomedical engineering or a related discipline.',
'2、有读博士意愿的优先；':'2. Applicants intending to pursue a PhD are preferred.',
'3、热爱科研工作、吃苦耐劳、认真负责；':'3. A passion for research, perseverance, diligence and responsibility.',
'4、具有良好的英文写作能力；':'4. Good English writing skills.',
'5、科研助理起始月薪6500-10000RMB，基于能力、经验及表现调整；享受过节费、每月餐补福利待遇；享受基本养老保险、基本医疗保险、失业保险、工伤保险、生育保险、住房公积金及住房补贴待遇；有继续深造意向的可以申请合作培养研究生项目。':'5. This archived notice lists a starting monthly salary of RMB 6,500-10,000, adjusted for ability, experience and performance. Benefits include holiday allowances, monthly meal allowances, statutory pension, medical, unemployment, work-injury and maternity insurance, a housing fund and housing subsidies. Applicants interested in further study may apply for joint postgraduate programs.',
'五、应聘方式':'5. How to Apply',
'个人简历+应聘岗位+发表文章+一页以内的研究计划，申请材料请发送至xilei@sustech.edu.cn，来信时请注明可到岗时间，邮件标题请注明“xxx应聘多功能光学影像实验室”，感谢您的关注！':'Email your CV, desired position, publications and a research proposal of no more than one page to xilei@sustech.edu.cn. State your earliest available start date and use the subject line "[Your name] - Application to the Multi-Functional Optical Imaging Lab". Thank you for your interest.'
});

Object.assign(english, {
  '按出版社地址规则生成，未逐条确认': 'Generated from publisher URL patterns; links have not been individually confirmed.',
  '已收录的 PDF 链接': 'Previously collected PDF link',
  '搜索找到的出版商 PDF 入口': 'Publisher PDF link found through search'
});

// Country labels in the original registration archive use standard region names.
const regions = 'CN HK MO TW KR JP US CA GB MY TH VN FR PH ID IT RU NZ NL SE AU DE SG FI DK IL AE NG AX AL AT BY BE BG CY EE FO GR HU IS IE LV LI LT LU MT MD MC ME NO PL PT RO SM RS SK SI ES CH UA AI BB BZ BM KY CR CU DM DO SV GD GP GT HT HN JM MQ MS NI PA PR KN LC VC TT TC VG VI AR BO BR CL CO EC FK GF GY PY PE SR UY VE AF AM AZ BH BD BT BN KH GE IN IR IQ JO KZ KW KG LA LB MV MN MM NP KP OM PK PS QA SA LK SY TJ TL TR TM UZ YE DZ AO BJ BW BF BI CM CV CF TD KM CG CD DJ EG GQ ER ET GA GM GH GN GW CI KE LS LR LY MG MW ML MR MU MA MZ NA NE RE RW ST SN SC SL SO ZA SS SD SZ TZ TG TN UG ZM ZW AS CK FJ PF GU KI MH FM NR NC NU NF MP PW PG WS SB TK TO TV VU WF VA'.split(' ');
try {
  const zh = new Intl.DisplayNames(['zh-CN'], {type:'region'});
  const en = new Intl.DisplayNames(['en'], {type:'region'});
  for (const region of regions) english[zh.of(region)] ??= en.of(region);
} catch { /* Core UI translations do not depend on region display names. */ }
const normalize = text => text.replace(/\s+/g, ' ').trim();
const normalized = new Map(Object.entries(english).map(([key,value]) => [normalize(key),value]));
const escapePattern = text => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const fragments = new RegExp(Object.keys(english).filter(Boolean).sort((a,b)=>b.length-a.length).map(escapePattern).join('|'), 'g');
const cache = new Map();
const preserveSpacing = (original, translated) => {
  const leading = original.match(/^\s*/)[0];
  const trailing = original.match(/\s*$/)[0];
  return (leading && !/^\s/.test(translated) ? leading : '')
    + translated
    + (trailing && !/\s$/.test(translated) ? trailing : '');
};
export function toEnglish(text) {
  if (typeof text !== 'string' || !/[\u3400-\u9fff]/.test(text)) return text;
  if (cache.has(text)) return cache.get(text);
  const exact = english[text] ?? normalized.get(normalize(text));
  let result;
  if (exact !== undefined) result = preserveSpacing(text, exact);
  else result = text.split('\n').map(line => {
    const full = normalized.get(normalize(line));
    if (full !== undefined) return preserveSpacing(line, full);
    return line.replace(/(\d{4})年(?:(\d{1,2})月)?(?:(\d{1,2})日)?/g, (_,year,month,day) => {
      if (!month) return year;
      const name = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][Number(month)-1];
      return day ? `${name} ${Number(day)}, ${year}` : `${name} ${year}`;
    }).replace(fragments, key => english[key]).replace(/：/g, ': ').replace(/；/g, '; ').replace(/，/g, ', ').replace(/。/g, '.').replace(/（/g, '(').replace(/）/g, ')');
  }).join('\n');
  if (cache.size > 6000) cache.clear();
  cache.set(text, result);
  return result;
}
